<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate\Hook\TripalCultivateHooks in trpcultivate/src/Hook/TripalCultivateHooks.php.
 */
#[LegacyHook]
function trpcultivate_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('trpcultivate.hooks')->help($route_name, $route_match);
}

/**
 * Implements hook_preprocess_page().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate\Hook\TripalCultivateThemeHooks in
 * trpcultivate/src/Hook/TripalCultivateThemeHooks.php.
 */
#[LegacyHook]
function trpcultivate_preprocess_page(&$variables) {
  \Drupal::service('trpcultivate.theme_hooks')->preprocessPage($variables);
}

/**
 * Implements hook_config_schema_info_alter().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate\Hook\TripalCultivateHooks in trpcultivate/src/Hook/TripalCultivateHooks.php.
 */
#[LegacyHook]
function trpcultivate_config_schema_info_alter(&$definitions) {
  \Drupal::service('trpcultivate.hooks')->configSchemaInfoAlter($definitions);
}

/**
 * Implements hook_theme().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate\Hook\TripalCultivateThemeHooks in
 * trpcultivate/src/Hook/TripalCultivateThemeHooks.
 */
#[LegacyHook]
function trpcultivate_theme($existing, $type, $theme, $path) {
  return \Drupal::service('trpcultivate.theme_hooks')->theme($existing, $type, $theme, $path);
}
