<?php

/**
 * @file
 * Install, update and uninstall functions for the Base API module.
 */

/**
 * Implements hook_install().
 */
function trpcultivate_install(): void {
  // Submit job to run the setup of the module.
  $current_user = \Drupal::currentUser();
  \Drupal::service('tripal.job')->create([
    'job_name' => t("Setup Tripal Cultivate Terms and Content Types"),
    'modulename' => 'trpcultivate',
    'callback' => ['Drupal\trpcultivate\Service\SetupModuleService', 'runSetupModuleTripalJob'],
    'arguments' => [],
    'uid' => $current_user->id(),
  ]);
}
