<?php

/**
 * @file
 * Install, update and uninstall functions for the Base API module.
 */

/**
 * Implements hook_requirements().
 */
function trpcultivate_requirements($phase) {
  $requirements = [];

  // Check Chado version and throw and error if the version is not compatible.
  if ($phase == 'install') {
    $chado_connection = new Drupal\tripal_chado\Database\ChadoConnection();
    $chado_schema_name = Drupal::config('tripal_chado.settings')
      ->get('default_schema');
    $chado_version = $chado_connection->findVersion($chado_schema_name, TRUE);

    if (version_compare($chado_version, '1.3.3.013') < 0) {
      $requirements['tripal_chado'] = [
        'title' => t('Chado version'),
        'value' => $chado_version,
        'description' => t('TripalCultivate requires Chado >= 1.3.3.013. Detected version: @version.', ['@version' => $chado_version]),
        'severity' => class_exists(\Drupal\Core\Extension\Requirement\RequirementSeverity::class) ? \Drupal\Core\Extension\Requirement\RequirementSeverity::Error : REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}

/**
 * Implements hook_install().
 */
function trpcultivate_install(): void {
  // Submit job to run the setup of the module.
  $current_user = \Drupal::currentUser();
  \Drupal::service('tripal.job')->create([
    'job_name' => t("Setup Tripal Cultivate Terms and Content Types"),
    'modulename' => 'trpcultivate',
    'callback' => ['Drupal\trpcultivate\Service\SetupModuleService', 'runSetupModuleTripalJob'],
    'arguments' => [],
    'uid' => $current_user->id(),
  ]);
}
